
package vista;

import java.awt.Color;
import javax.swing.JOptionPane;
import accesoADatos.*;
import controlador.Control;
import modelo.*;



public class ventanaRegistro extends javax.swing.JFrame {
    String usuario1;
    String nombre1; 
    String apellido1;    
    String email1;    
    String celular2;  
    String fechaNa1;  
    String clave1;
    VentanaPrincipal v1;
    controlador.Control controlador = new Control();
    public participanteDAO participantes;
  
    public ventanaRegistro() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        ImagenPersona = new javax.swing.JLabel();
        Bienvenido = new javax.swing.JLabel();
        ImagenFondo = new javax.swing.JLabel();
        Principal = new javax.swing.JPanel();
        RegistreP = new javax.swing.JLabel();
        CompleteP = new javax.swing.JLabel();
        Usuario = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        Nombre = new javax.swing.JLabel();
        txtnomb = new javax.swing.JTextField();
        Apellido = new javax.swing.JLabel();
        txtapell = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        Celular = new javax.swing.JLabel();
        txtcell = new javax.swing.JTextField();
        Fecha = new javax.swing.JLabel();
        txtfecha = new javax.swing.JTextField();
        clave = new javax.swing.JLabel();
        txtclave = new javax.swing.JTextField();
        Registrar = new javax.swing.JButton();

        setLocationByPlatform(true);
        setResizable(false);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setMinimumSize(new java.awt.Dimension(840, 500));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ImagenPersona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImagenPersona.setIcon(new javax.swing.ImageIcon("C:\\Users\\David\\Desktop\\Reto5\\Imagenes-P\\User.png")); // NOI18N
        Background.add(ImagenPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 240, 150));

        Bienvenido.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        Bienvenido.setForeground(new java.awt.Color(255, 255, 255));
        Bienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bienvenido.setText("Participantes");
        Background.add(Bienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 240, 60));

        ImagenFondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\David\\Desktop\\Reto5\\Imagenes-P\\Background.jpg")); // NOI18N
        Background.add(ImagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 510));

        Principal.setBackground(new java.awt.Color(255, 255, 255));
        Principal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Principal.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        Principal.setDoubleBuffered(false);

        RegistreP.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        RegistreP.setText("Registre los Participantes");

        CompleteP.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        CompleteP.setForeground(new java.awt.Color(153, 153, 153));
        CompleteP.setText("Complete la informacion sobre los Participantes");

        Usuario.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        Usuario.setText("Usuario");

        txtuser.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        Nombre.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        Nombre.setText("Nombre");

        txtnomb.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        Apellido.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        Apellido.setText("Apellido");

        txtapell.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtapell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapellActionPerformed(evt);
            }
        });

        Email.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        Email.setText("Email");

        txtemail.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N

        Celular.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        Celular.setText("Celular");

        txtcell.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N

        Fecha.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        Fecha.setText("Fecha de Nacimiento");

        txtfecha.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        txtfecha.setForeground(new java.awt.Color(102, 102, 102));
        txtfecha.setText("AAAA-MM-DD");
        txtfecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtfechaMousePressed(evt);
            }
        });
        txtfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfechaActionPerformed(evt);
            }
        });

        clave.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        clave.setText("Clave");

        txtclave.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        txtclave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtclaveActionPerformed(evt);
            }
        });

        Registrar.setBackground(new java.awt.Color(63, 137, 164));
        Registrar.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        Registrar.setForeground(new java.awt.Color(255, 255, 255));
        Registrar.setText("Registrar");
        Registrar.setToolTipText("");
        Registrar.setBorder(null);
        Registrar.setBorderPainted(false);
        Registrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PrincipalLayout = new javax.swing.GroupLayout(Principal);
        Principal.setLayout(PrincipalLayout);
        PrincipalLayout.setHorizontalGroup(
            PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrincipalLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PrincipalLayout.createSequentialGroup()
                        .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clave, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PrincipalLayout.createSequentialGroup()
                                .addComponent(txtclave, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PrincipalLayout.createSequentialGroup()
                        .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CompleteP)
                            .addComponent(RegistreP, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PrincipalLayout.createSequentialGroup()
                                .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(PrincipalLayout.createSequentialGroup()
                                        .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(113, 113, 113))
                                    .addGroup(PrincipalLayout.createSequentialGroup()
                                        .addComponent(txtuser)
                                        .addGap(33, 33, 33)))
                                .addGap(14, 14, 14)
                                .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtapell, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PrincipalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PrincipalLayout.createSequentialGroup()
                        .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Email, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtemail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtnomb, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtcell, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Celular, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(Fecha)
                        .addGap(33, 33, 33))))
        );
        PrincipalLayout.setVerticalGroup(
            PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RegistreP, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CompleteP)
                .addGap(82, 82, 82)
                .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre)
                    .addComponent(Apellido)
                    .addComponent(Usuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnomb, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtapell, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Email)
                    .addComponent(Fecha)
                    .addComponent(Celular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcell, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(clave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Registrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtclave, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        Background.add(Principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 560, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtapellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellActionPerformed

    private void txtclaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtclaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtclaveActionPerformed

    private void txtfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfechaActionPerformed

    private void RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarActionPerformed
        controlador.accionesVRegistro(this, evt);
        
        
    }//GEN-LAST:event_RegistrarActionPerformed

    private void txtfechaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtfechaMousePressed
        if(txtfecha.getText().equals("AAAA-MM-DD")){
        txtfecha.setText("");
        txtfecha.setForeground(Color.BLACK);
        
        }
        
    
    }//GEN-LAST:event_txtfechaMousePressed
    
    public void agregar(){

        usuario1  = txtuser.getText();
        nombre1   = txtnomb.getText();
        apellido1 = txtapell.getText();   
        email1    = txtemail.getText();
        celular2  = txtcell.getText();
        fechaNa1  = txtfecha.getText();
        clave1    = txtclave.getText();
        
        boolean comprobacion = celular2.matches("[+-]?\\d*(\\.\\d+)?");
        
        if(clave1.equals("") || usuario1.equals("") || nombre1.equals("") || apellido1.contentEquals("") || email1.equals("") || celular2.equals("") || fechaNa1.equals("AAAA-MM-DD")){
            JOptionPane.showMessageDialog(null, "Faltan campos por llenar");
            
        }
        if(comprobacion == false){
            JOptionPane.showMessageDialog(null, "El campo celular contiene letras");
            
        }else{
            long celular1 = Long.parseLong(txtcell.getText());
            participanteDAO participante = new participanteDAO();
            ParticipanteModel participante1 = new ParticipanteModel(usuario1, nombre1, apellido1, email1, celular1, clave1, fechaNa1);
            participante.insertParticipante(participante1);
            limpiarcajas();
         
        }   
     }
   
    
    public void limpiarcajas(){
        
        txtuser.setText("");
        txtnomb.setText("");
        txtapell.setText("");   
        txtemail.setText("");
        txtcell.setText("");
        txtfecha.setText("AAAA-MM-DD");
        txtfecha.setForeground(new Color(102,102,102));
        txtclave.setText("");
        
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido;
    private javax.swing.JPanel Background;
    private javax.swing.JLabel Bienvenido;
    private javax.swing.JLabel Celular;
    private javax.swing.JLabel CompleteP;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Fecha;
    private javax.swing.JLabel ImagenFondo;
    private javax.swing.JLabel ImagenPersona;
    private javax.swing.JLabel Nombre;
    private javax.swing.JPanel Principal;
    public javax.swing.JButton Registrar;
    private javax.swing.JLabel RegistreP;
    private javax.swing.JLabel Usuario;
    private javax.swing.JLabel clave;
    public static javax.swing.JTextField txtapell;
    public static javax.swing.JTextField txtcell;
    public static javax.swing.JTextField txtclave;
    public static javax.swing.JTextField txtemail;
    public static javax.swing.JTextField txtfecha;
    public static javax.swing.JTextField txtnomb;
    public static javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
